production:
  server: "https://test-private-pub3693.herokuapp.com/faye"

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension.

  secret_token: edebf2b26f55afe8da9769fe99c9c4139a135edb256361a4c0fc9b002fbc878a
  signature_expiration: 3600 # one day
